title: Damek Davis' Website
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Add GitHub settings
github:
  owner: damek
  repository: STAT-4830

# Configure collections
collections:
  sections:
    output: true
    permalink: /STAT-4830/section/:path/

# Plugin settings
plugins:
  - jekyll-github-api
