title: Damek Davis' Website
show_downloads: true
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Add GitHub settings
github:
  owner: damek

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude directories and patterns
exclude:
  - STAT-4830
  - STAT-4830/**
  - STAT-4830/section_0.md
  - "**/STAT-4830/**"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Link checking settings
relative_links:
  enabled: true
  collections: false

# Tell Jekyll which links to skip checking
skip_check_links:
  - STAT-4830
  - STAT-4830/*

# …your existing config…

collections:
  random:
    output: true          # render each file
    permalink: /random/:slug/  # short, mnemonic URLs like /u/gelu-vs-sigmoid/

defaults:                 # make them inherit your default.html wrapper
  -
    scope:
      path: "_random"
      type: random
    values:
      layout: random_note
      title: ""           # optional, you can set per-file
